### ISSUE TITLE
Setting chunk size parameter to be larger than dataset size results in ValueError

### ISSUE THREAD

**Issue by melissawm** [Quansight/versioned-hdf5#34]
Ideally, if the chunk size is too large, we should be able to ignore it or set the chunk size automatically (as the size of the initial dataset, for example). However, as other versions might have data of different sizes, this large chunk size parameter might be relevant for some versions only.

Example:

```python
>>> filename = "test.h5"                                                                                                                                                           
>>> import h5py                                                                                                                                                                    
>>> from versioned_hdf5.api import VersionedHDF5File                                                                                                                               
>>> import numpy as np
>>> f = h5py.File(filename, 'w')                                                                                                                                                   
>>> file = VersionedHDF5File(f)                                                                                                                                                    
>>> with file.stage_version("initial_version") as group:
...     val = group.create_dataset("test", data=np.random.rand(5000), dtype=(np.dtype('float64')), chunks=(2**14,)) 
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/melissa/projects/versioned-hdf5/versioned_hdf5/api.py", line 180, in create_dataset
    data = super().create_dataset(name, **kwds)
  File "/opt/miniconda3/envs/vhdf5/lib/python3.8/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/opt/miniconda3/envs/vhdf5/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 104, in make_new_dset
    raise ValueError(errmsg)
ValueError: Chunk shape must not be greater than data shape in any dimension. (16384,) is not compatible with (5000,)
>>> 
```

**Comment by asmeurer** [comment]
This is a rather odd limitation of h5py. I wonder why it is there. Anyway, I have removed it in #36 (which isn't yet finished).
